### ISSUE TITLE
ERROR [label="unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'" fontcolor=red color=white];

### ISSUE THREAD

**Issue by backbone10** [legrandlegrand/revj2#1]
Hi, I think this could be a bug, maybe someone can confirm or help ?

I always get this Error message if I try to generate a diagram (I use IDLE shell 3.9.4)

Thanks for your support

**Comment by legrandlegrand** [comment]
Hi, 
this version is currently working with python 2.8 only.
If you want a python 3+ compatibility you may try https://github.com/hippysurfer/revj

Regards
PAscal

**Comment by legrandlegrand** [comment]
a revj version compatible with python 3 with a new version of pyparsing has been commited today,
you may want to try it !
